### PR TITLE
Example for harsha-simhadri/big-ann-benchmarks/issues/20

### PR DESCRIPTION
**Pull request by alexklibisz**
This PR serves as a companion to the discussion at https://github.com/harsha-simhadri/big-ann-benchmarks/issues/20 and is not intended to be merged.

The PR updates the latest Elastiknn version and adds timing instrumentation to the Elastiknn `L2LshModel` in `ann_benchmarks/algorithms/elastiknn.py` in order to measure the overhead of a client/server model in ann-benchmarks.

The overhead is measured by measuring and comparing the time from the client's perspective and the time from the server's perspective. Client time is measured using the Python perf_counter() method. Server time is measured using the `took` value from the Elasticsearch response. [According to the ES docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-search.html#search-api-response-body): "This value is calculated by measuring the time elapsed between receipt of a request on the coordinating node and the time at which the coordinating node is ready to send the response."

To summarize: **the total overhead for a model w/ recall@100 = 0.91 on the Fashion Mnist dataset is _40%_.**

In other words, for every 10ms of query time, 4ms is spent on request marshaling and HTTP communication. Note that this is actually a generous interpretation of overhead, as the time spent unmarshaling the JSON request is included in the `took` value returned from Elasticsearch. In a single language setup, there would be 0 time spent on JSON unmarshaling.

Here are the steps to reproduce and logs showing the 40% value:

```
$ docker build -t ann-benchmarks -f install/Dockerfile .
...
$ docker build -t ann-benchmarks-elastiknn -f install/Dockerfile.elastiknn .
...
$ python run.py --algorithm elastiknn-l2lsh --dataset fashion-mnist-784-euclidean --max-n-algorithms 1 --runs 2 --count 100 --force
2021-08-22 20:05:55,723 - annb - INFO - running only elastiknn-l2lsh
2021-08-22 20:05:55,781 - annb - INFO - Order: [Definition(algorithm='elastiknn-l2lsh', constructor='L2Lsh', module='ann_benchmarks.algorithms.elastiknn', docker_tag='ann-benchmarks-elastiknn', arguments=[75, 4, 7], query_argument_groups=[[1000, 3]], disabled=False)]
2021-08-22 20:05:56,151 - annb.cd2afd4764 - INFO - Created container cd2afd4764: CPU limit 1, mem limit 26528525056, timeout 7200, command ['--dataset', 'fashion-mnist-784-euclidean', '--algorithm', 'elastiknn-l2lsh', '--module', 'ann_benchmarks.algorithms.elastiknn', '--constructor', 'L2Lsh', '--runs', '2', '--count', '100', '[75, 4, 7]', '[1000, 3]']
2021-08-22 20:05:56,155 - annb.cd2afd4764 - INFO -  * Starting Elasticsearch Server
2021-08-22 20:05:56,156 - annb.cd2afd4764 - INFO - sysctl: setting key "vm.max_map_count": Read-only file system
2021-08-22 20:06:03,878 - annb.cd2afd4764 - INFO -    ...done.
2021-08-22 20:06:04,865 - annb.cd2afd4764 - INFO - [75, 4, 7]
2021-08-22 20:06:04,865 - annb.cd2afd4764 - INFO - Trying to instantiate ann_benchmarks.algorithms.elastiknn.L2Lsh([75, 4, 7])
2021-08-22 20:06:05,003 - annb.cd2afd4764 - INFO - Waiting for elasticsearch health endpoint...
2021-08-22 20:06:20,346 - annb.cd2afd4764 - INFO - Elasticsearch is ready
2021-08-22 20:06:21,169 - annb.cd2afd4764 - INFO - got a train set of size (60000 * 784)
2021-08-22 20:06:21,169 - annb.cd2afd4764 - INFO - got 10000 queries
2021-08-22 20:06:21,526 - annb.cd2afd4764 - INFO - eknn-l2lsh-L=75-k=4-w=7: indexing 60000 vectors
2021-08-22 20:06:21,603 - annb.cd2afd4764 - INFO - index was not given, using elastiknn-1629677181 instead
2021-08-22 20:07:57,467 - annb.cd2afd4764 - INFO - Built index in 95.9407217502594
2021-08-22 20:07:57,467 - annb.cd2afd4764 - INFO - Index size:  6552.0
2021-08-22 20:07:57,467 - annb.cd2afd4764 - INFO - Running query argument group 1 of 1...
2021-08-22 20:07:57,468 - annb.cd2afd4764 - INFO - Run 1/2...
2021-08-22 20:08:12,891 - annb.cd2afd4764 - INFO - Total duration client = 13 seconds
2021-08-22 20:08:12,891 - annb.cd2afd4764 - INFO - Total duration server = 7 seconds
2021-08-22 20:08:12,891 - annb.cd2afd4764 - INFO - Overhead = 45 percent
2021-08-22 20:08:12,893 - annb.cd2afd4764 - INFO - Processed 1000/10000 queries...
2021-08-22 20:08:23,620 - annb.cd2afd4764 - INFO - Total duration client = 21 seconds
2021-08-22 20:08:23,621 - annb.cd2afd4764 - INFO - Total duration server = 12 seconds
2021-08-22 20:08:23,621 - annb.cd2afd4764 - INFO - Overhead = 43 percent
2021-08-22 20:08:23,623 - annb.cd2afd4764 - INFO - Processed 2000/10000 queries...
2021-08-22 20:08:33,676 - annb.cd2afd4764 - INFO - Total duration client = 29 seconds
2021-08-22 20:08:33,676 - annb.cd2afd4764 - INFO - Total duration server = 17 seconds
2021-08-22 20:08:33,676 - annb.cd2afd4764 - INFO - Overhead = 42 percent
2021-08-22 20:08:33,678 - annb.cd2afd4764 - INFO - Processed 3000/10000 queries...
2021-08-22 20:08:43,912 - annb.cd2afd4764 - INFO - Total duration client = 36 seconds
2021-08-22 20:08:43,913 - annb.cd2afd4764 - INFO - Total duration server = 21 seconds
2021-08-22 20:08:43,913 - annb.cd2afd4764 - INFO - Overhead = 41 percent
2021-08-22 20:08:43,915 - annb.cd2afd4764 - INFO - Processed 4000/10000 queries...
2021-08-22 20:08:54,823 - annb.cd2afd4764 - INFO - Total duration client = 45 seconds
2021-08-22 20:08:54,824 - annb.cd2afd4764 - INFO - Total duration server = 26 seconds
2021-08-22 20:08:54,824 - annb.cd2afd4764 - INFO - Overhead = 42 percent
2021-08-22 20:08:54,826 - annb.cd2afd4764 - INFO - Processed 5000/10000 queries...
2021-08-22 20:09:05,598 - annb.cd2afd4764 - INFO - Total duration client = 53 seconds
2021-08-22 20:09:05,598 - annb.cd2afd4764 - INFO - Total duration server = 31 seconds
2021-08-22 20:09:05,599 - annb.cd2afd4764 - INFO - Overhead = 42 percent
2021-08-22 20:09:05,601 - annb.cd2afd4764 - INFO - Processed 6000/10000 queries...
2021-08-22 20:09:16,043 - annb.cd2afd4764 - INFO - Total duration client = 60 seconds
2021-08-22 20:09:16,043 - annb.cd2afd4764 - INFO - Total duration server = 35 seconds
2021-08-22 20:09:16,043 - annb.cd2afd4764 - INFO - Overhead = 42 percent
2021-08-22 20:09:16,046 - annb.cd2afd4764 - INFO - Processed 7000/10000 queries...
2021-08-22 20:09:26,261 - annb.cd2afd4764 - INFO - Total duration client = 68 seconds
2021-08-22 20:09:26,262 - annb.cd2afd4764 - INFO - Total duration server = 40 seconds
2021-08-22 20:09:26,262 - annb.cd2afd4764 - INFO - Overhead = 42 percent
2021-08-22 20:09:26,264 - annb.cd2afd4764 - INFO - Processed 8000/10000 queries...
2021-08-22 20:09:36,331 - annb.cd2afd4764 - INFO - Total duration client = 76 seconds
2021-08-22 20:09:36,331 - annb.cd2afd4764 - INFO - Total duration server = 44 seconds
2021-08-22 20:09:36,331 - annb.cd2afd4764 - INFO - Overhead = 42 percent
2021-08-22 20:09:36,334 - annb.cd2afd4764 - INFO - Processed 9000/10000 queries...
2021-08-22 20:09:45,728 - annb.cd2afd4764 - INFO - Total duration client = 82 seconds
2021-08-22 20:09:45,728 - annb.cd2afd4764 - INFO - Total duration server = 48 seconds
2021-08-22 20:09:45,728 - annb.cd2afd4764 - INFO - Overhead = 42 percent
2021-08-22 20:09:45,730 - annb.cd2afd4764 - INFO - Processed 10000/10000 queries...
2021-08-22 20:09:45,735 - annb.cd2afd4764 - INFO - Run 2/2...
2021-08-22 20:09:55,354 - annb.cd2afd4764 - INFO - Total duration client = 89 seconds
2021-08-22 20:09:55,354 - annb.cd2afd4764 - INFO - Total duration server = 52 seconds
2021-08-22 20:09:55,354 - annb.cd2afd4764 - INFO - Overhead = 41 percent
2021-08-22 20:09:55,357 - annb.cd2afd4764 - INFO - Processed 1000/10000 queries...
2021-08-22 20:10:04,832 - annb.cd2afd4764 - INFO - Total duration client = 96 seconds
2021-08-22 20:10:04,832 - annb.cd2afd4764 - INFO - Total duration server = 57 seconds
2021-08-22 20:10:04,832 - annb.cd2afd4764 - INFO - Overhead = 41 percent
2021-08-22 20:10:04,835 - annb.cd2afd4764 - INFO - Processed 2000/10000 queries...
2021-08-22 20:10:14,021 - annb.cd2afd4764 - INFO - Total duration client = 103 seconds
2021-08-22 20:10:14,021 - annb.cd2afd4764 - INFO - Total duration server = 61 seconds
2021-08-22 20:10:14,021 - annb.cd2afd4764 - INFO - Overhead = 41 percent
2021-08-22 20:10:14,023 - annb.cd2afd4764 - INFO - Processed 3000/10000 queries...
2021-08-22 20:10:23,376 - annb.cd2afd4764 - INFO - Total duration client = 110 seconds
2021-08-22 20:10:23,376 - annb.cd2afd4764 - INFO - Total duration server = 65 seconds
2021-08-22 20:10:23,376 - annb.cd2afd4764 - INFO - Overhead = 41 percent
2021-08-22 20:10:23,378 - annb.cd2afd4764 - INFO - Processed 4000/10000 queries...
2021-08-22 20:10:32,627 - annb.cd2afd4764 - INFO - Total duration client = 116 seconds
2021-08-22 20:10:32,627 - annb.cd2afd4764 - INFO - Total duration server = 69 seconds
2021-08-22 20:10:32,627 - annb.cd2afd4764 - INFO - Overhead = 41 percent
2021-08-22 20:10:32,629 - annb.cd2afd4764 - INFO - Processed 5000/10000 queries...
2021-08-22 20:10:41,793 - annb.cd2afd4764 - INFO - Total duration client = 123 seconds
2021-08-22 20:10:41,793 - annb.cd2afd4764 - INFO - Total duration server = 73 seconds
2021-08-22 20:10:41,794 - annb.cd2afd4764 - INFO - Overhead = 41 percent
2021-08-22 20:10:41,796 - annb.cd2afd4764 - INFO - Processed 6000/10000 queries...
2021-08-22 20:10:51,334 - annb.cd2afd4764 - INFO - Total duration client = 130 seconds
2021-08-22 20:10:51,335 - annb.cd2afd4764 - INFO - Total duration server = 77 seconds
2021-08-22 20:10:51,335 - annb.cd2afd4764 - INFO - Overhead = 41 percent
2021-08-22 20:10:51,337 - annb.cd2afd4764 - INFO - Processed 7000/10000 queries...
2021-08-22 20:11:00,781 - annb.cd2afd4764 - INFO - Total duration client = 137 seconds
2021-08-22 20:11:00,782 - annb.cd2afd4764 - INFO - Total duration server = 81 seconds
2021-08-22 20:11:00,782 - annb.cd2afd4764 - INFO - Overhead = 41 percent
2021-08-22 20:11:00,785 - annb.cd2afd4764 - INFO - Processed 8000/10000 queries...
2021-08-22 20:11:10,103 - annb.cd2afd4764 - INFO - Total duration client = 143 seconds
2021-08-22 20:11:10,103 - annb.cd2afd4764 - INFO - Total duration server = 85 seconds
2021-08-22 20:11:10,103 - annb.cd2afd4764 - INFO - Overhead = 41 percent
2021-08-22 20:11:10,105 - annb.cd2afd4764 - INFO - Processed 9000/10000 queries...
2021-08-22 20:11:19,274 - annb.cd2afd4764 - INFO - Total duration client = 150 seconds
2021-08-22 20:11:19,274 - annb.cd2afd4764 - INFO - Total duration server = 89 seconds
2021-08-22 20:11:19,275 - annb.cd2afd4764 - INFO - Overhead = 40 percent
2021-08-22 20:11:19,277 - annb.cd2afd4764 - INFO - Processed 10000/10000 queries...
$ sudo chown -R $(whoami):$(whoami) results/
$ python plot.py --dataset fashion-mnist-784-euclidean --recompute --count 100 -o out.png
Computing knn metrics
  0:                                 eknn-l2lsh-L=75-k=4-w=7_candidates=1000_probes=3        0.912      147.662
```

### CODE REVIEW

**Comment by alexklibisz** [comment]
If you drop the CPU constraint (comment out line 242 in runner.py), the overhead drops to about 37 percent. To me this indicates part of the overhead is spent swapping between the Python process and the Elasticsearch process.

```
diff --git a/ann_benchmarks/runner.py b/ann_benchmarks/runner.py
index 75b8b7d..118532f 100644
--- a/ann_benchmarks/runner.py
+++ b/ann_benchmarks/runner.py
@@ -239,7 +239,7 @@ def run_docker(definition, dataset, count, runs, timeout, batch, cpu_limit,
             os.path.abspath('results'):
                 {'bind': '/home/app/results', 'mode': 'rw'},
         },
-        cpuset_cpus=cpu_limit,
+        # cpuset_cpus=cpu_limit,
         mem_limit=mem_limit,
         detach=True)
     logger = logging.getLogger(f"annb.{container.short_id}")
```

```
2021-08-22 20:39:18,146 - annb.2276b9a803 - INFO - Processed 9000/10000 queries...
2021-08-22 20:39:27,577 - annb.2276b9a803 - INFO - Total duration client = 140 seconds
2021-08-22 20:39:27,577 - annb.2276b9a803 - INFO - Total duration server = 88 seconds
2021-08-22 20:39:27,577 - annb.2276b9a803 - INFO - Overhead = 37 percent
2021-08-22 20:39:27,580 - annb.2276b9a803 - INFO - Processed 10000/10000 queries...
```

**Comment by sourcesync** [comment]
Thanks for the code.

It took a sec to find the definition of the ES 'took' field, but I found [this](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-your-data.html):

> The took time in the response contains the milliseconds that this request took for processing, beginning quickly after the node received the query, up until all search related work is done and before the above JSON is returned to the client. This means it includes the time spent waiting in thread pools, executing a distributed search across the whole cluster and gathering all the results.

So, just guessing here, it sounds like much of the additional overhead is in the HTTP communication (including the serialization/deserialization for the HTTP payloads. ). Is that your assessment as well?

**Comment by alexklibisz** [comment]
> Thanks for the code.

Always happy to code :)

> It took a sec to find the definition of the ES 'took' field, but I found [this](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-your-data.html):

I included a link in the PR description, see here: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-search.html#search-api-response-body

image

> So, just guessing here, it sounds like much of the additional overhead is in the HTTP communication (including the serialization/deserialization for the HTTP payloads. ). Is that your assessment as well?

Right, we could dig deeper in terms of profiling, but the Elastic python client is basically just serializing JSON and sending HTTP requests. Also see my original comments in the PR description.

**Comment by sourcesync** [comment]
I'm curious, is there a way to store the query set first in ES and then perform search using a reference to the query set?  If so, then if this can be done as a preprocesing step to the actual "search" we eliminate the likely large cost of binary->serialize to HTTP->deserialize back binary.

**Comment by alexklibisz** [comment]
Hmm, maybe. I could create another index hosting the query vectors and use an indexed vector query (basically a query that says "my query vector is at index X, id y"). This is only possible if all of the queries are available up-front. It would save whatever time is spent serializing the vector to JSON.

**Comment by sourcesync** [comment]
I think it would (if it's possible.)  That said...it would not likely
account for the cost of serializing and deserializing the results array of
indices.  Presumably that should be a good fraction of the cost of
marshaling the large batch input array.

**Comment by alexklibisz** [comment]
I think the query pre-storage would have some useful effect, but it's adding more complexity and not really subtracting the actual problem. I'll start tinkering this week with some ways to make (big-)ann-benchmarks language agnostic, without disrupting the existing Python model. No pressure or expectation to go that direction. We'll see how it looks.

**Comment by alexklibisz** [comment]
Closing as this was solved as part of https://github.com/harsha-simhadri/big-ann-benchmarks/issues/20.

**Pull request closed without merging**
